[versions]
ktor = "3.1.3"

[libraries]
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback = { "module" = "ch.qos.logback:logback-classic", version="1.5.18" }

[plugins]
korge = { id = "com.soywiz.korge", version = "6.0.0" }
#korge = { id = "com.soywiz.korge", version = "999.0.0.999" }
