[versions]
ktor = "1.3.1"

[libraries]
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback = { "module" = "ch.qos.logback:logback-classic", version="1.2.3" }


[plugins]
#korge = { id = "com.soywiz.korge", version = "3.4.0" }
korge = { id = "com.soywiz.korge", version = "999.0.0.999" }
